{% set name = "hunter" %}
{% set version = "3.1.3" %}
{% set sha256 = "3c293580bba8489c4188fd39c33089a5697800bd3b37700869d6070de1805a28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - hunter-trace = hunter.remote:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - colorama
    - manhole  # [not win]

test:
  imports:
    - hunter
    - hunter.backports
  commands:
    - hunter-trace --help  # [not win]

about:
  home: https://github.com/ionelmc/python-hunter
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hunter is a flexible code tracing toolkit
