appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ponjbAgxbseCPMQLsKU+P438sf98OHbP7hROLRgmOrym1WrVbdx+B3CIxKJ2CPBHqV79KCw7oKUbiYFJyIdrpPbLFs+604GUZ9eIRh2bVzHiB8wpcpkMo/RXidNKN8dM6eun6SwUBE96EY9egVOS1B8A88FwY21MYM7TfS3DBtyzmTzSBob75nSejNvdMxyAL6r8jeMHUuHcZ8MkpWeU+Nm+aVxx8bzLAI1p4JeAdn91Nj6NlQ+sU4l1kM7EfQUwRiPMNOk9knq5mq2YA53hfgsiQFewsryq+2aG347UwqwoJdnrsE6blpFKN/5GA8m9DAlYcuLhfCe6TaHKNIXU9TBiSb6AEoS4WnWW3KSSH1Jo3IJqkQkzbVWmCtKz/u0xunBkf0/6i1OmVql96LpmLGb2mcRzXSR5UvvNVLQew4SvJN/QZAxMzMy5ilKBcFrwKTAlN8aMOdFQWBc67iRrzJ/IKlKKZOCTfzH71o7dlyTqwdLp2ctdRzUV9vmGiw8fjricFfEFFpjJN+GXykjG8k3BtdJLEPCJvfcXvkUvZp4thtG8xOhiKi4RBFXni4da7+/9G8puo23EcW5+nwpsd0Pi4iqX2beI2lEfMFhfGnr/kc1qcsfGXikETsaHhZAiqyuhMX9vM8cll3s/KoQaKYeExYkpqNOeaBkEUvSY2eY=}
provider:
  win: azure
